targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake